# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-01 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='detail',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
