# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-01 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_orders_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='detail',
            new_name='mixins',
        ),
    ]
